// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroLibro.Context;

#nullable disable

namespace RegistroLibro.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260926194043_RegistroPrestamosLibros")]
    partial class RegistroPrestamosLibros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RegistroLibro.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 1,
                            Direccion = "Calle Central #12",
                            Email = "juan.perez@email.com",
                            FechaNacimiento = new DateOnly(2002, 5, 14),
                            Nombres = "Juan Pérez"
                        },
                        new
                        {
                            EstudianteId = 2,
                            Direccion = "Av. Libertad #45",
                            Email = "maria.rodriguez@email.com",
                            FechaNacimiento = new DateOnly(2003, 8, 22),
                            Nombres = "María Rodríguez"
                        });
                });

            modelBuilder.Entity("RegistroLibro.Models.Libros", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoPublicacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibroId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            AnoPublicacion = 1967,
                            Autor = "Gabriel García Márquez",
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            LibroId = 2,
                            AnoPublicacion = 1605,
                            Autor = "Miguel de Cervantes",
                            Titulo = "Don Quijote de la Mancha"
                        },
                        new
                        {
                            LibroId = 3,
                            AnoPublicacion = 1943,
                            Autor = "Antoine de Saint-Exupéry",
                            Titulo = "El Principito"
                        });
                });

            modelBuilder.Entity("RegistroLibro.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrestamoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("LibroId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("RegistroLibro.Models.Prestamos", b =>
                {
                    b.HasOne("RegistroLibro.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroLibro.Models.Libros", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Libro");
                });
#pragma warning restore 612, 618
        }
    }
}
