// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RegistroLibro.Context;

#nullable disable

namespace RegistroLibro.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");
            modelBuilder.Entity("RegistroLibro.Models.Estudiante", b =>
            {
                b.Property<int>("EstudianteId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Direccion").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                b.Property<DateOnly>("FechaNacimiento").HasColumnType("TEXT");
                b.Property<string>("Nombres").IsRequired().HasColumnType("TEXT");
                b.HasKey("EstudianteId");
                b.ToTable("Estudiantes");
            });
        }
    }
}